
# if trusty is not used compilation is killed (out or mem)
sudo: required
dist: trusty

language: python

git:
  depth: 1

cache:
  apt: true

python:
  - "3.5"



# command to install dependencies
install: 
  - cd ..
  - pip3 install coveralls
  - git clone https://github.com/Nic30/HWToolkit.git
  - git clone https://github.com/Nic30/hwtLib.git
  - cd HWToolkit
  - python3 setup.py install
  - cd ../hwtLib
  - python3 setup.py install

# command to run tests
script: 
  - python3 -m pytest hwtLib/tests/all.py --doctest-modules -v

after_success:
  - coveralls
