addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test

    packages:
    # install toolchains
    - gcc-5.4
    - g++-5.4

compiler:
  - gcc-5.4

git:
  depth: 1

env:
  - CC=gcc-5 CCX=g++-5

language: python
python:
  - "3.5"

# command to install dependencies
install: 
  - gcc --version
  - echo $CC 
  - cd ..
  - git clone https://github.com/Nic30/HWToolkit.git
  - cd HWToolkit
  - python3 setup.py install
  - cd ../hwtLib
  - python3 setup.py install

# command to run tests
script: 
  - python3 hwtLib/tests/all.py
