language: python
git:
  depth: 1

# clang is required because there is not enought ram for gcc
compiler: clang
python:
  - "3.5"
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise-3.8
      packages:
         - g++-6
         - clang-3.8
env: CC=clang-3.8 CXX=clang-3.8

# command to install dependencies
install: 
  - cd ..
  - git clone https://github.com/Nic30/HWToolkit.git
  - cd HWToolkit
  - python3 setup.py install
  - cd ../hwtLib
  - python3 setup.py install

# command to run tests
script: 
  - python3 hwtLib/tests/all.py
