name: rtd_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - icu=68.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libuv=1.40.0
  - ncurses=6.2
  - nodejs=14.15.1
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.8.5
  - python_abi=3.8
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aafigure==0.6
    - alabaster==0.7.12
    - babel==2.9.0
    - chardet==4.0.0
    - docutils==0.16
    - idna==2.10
    - imagesize==1.2.0
    - pytz==2021.1
    - requests==2.25.1
    - snowballstemmer==2.1.0
    - sphinx==3.5.1
    - sphinx-bootstrap-theme==0.7.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - urllib3==1.26.3
    - "-r https://raw.githubusercontent.com/Nic30/hwtLib/master/doc/requirements.doc.txt"
    - git+git://github.com/Nic30/hwtLib#egg=hwtLib
